# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI="5"

inherit distutils

MY_P="${PN}-${PV}"

DESCRIPTION="Tools for working with the OFX (Open Financial Exchange) file format"
HOMEPAGE="http://sites.google.com/site/ofxparse"
SRC_URI="https://pypi.python.org/packages/source/o/ofxparse/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

RDEPEND="
dev-python/nose
dev-python/beautifulsoup:4
"
