# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_P="${PN}-${PV}"

DESCRIPTION="OFX client for dowloading transactions from banks"
HOMEPAGE="https://github.com/captin411/ofxclient"
SRC_URI="https://pypi.python.org/packages/source/o/ofxclient/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND=">=dev-lang/python-2.7"

RDEPEND="
${DEPEND}
dev-python/keyring
dev-python/ofxhome
>dev-python/ofxparse-0.8
>=dev-python/beautifulsoup-3.0
"

src_unpack() {
	unpack ${A}
	cd "${S}"
	epatch ${FILESDIR}/${P}-*.patch
}
