# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

inherit distutils

MY_P="${PN}-${PV}"

DESCRIPTION="ofxhome.com financial institution lookup REST client"
HOMEPAGE="https://github.com/captin411/ofxhome"
SRC_URI="https://pypi.python.org/packages/source/o/ofxhome/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

